global using ProtonedMusicAPI.Database.Entities;
global using ProtonedMusicAPI.Database;
global using ProtonedMusicAPI.Interfaces.IUser;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using ProtonedMusicAPI.DTO.UserDTO;
global using ProtonedMusicAPI.Helper;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
